name: CI Build & Test

on:
  push:
    branches:
      - "**"  # run on all branches
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Install deps
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Build binaries
        run: |
          mkdir -p build
          GOOS=linux   GOARCH=amd64 go build -o build/syshealth-linux-amd64
          GOOS=darwin  GOARCH=amd64 go build -o build/syshealth-darwin-amd64
          GOOS=darwin  GOARCH=arm64 go build -o build/syshealth-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o build/syshealth-windows-amd64.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: syshealth-binaries
          path: build/*

